import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "de" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>("de");

  useEffect(() => {
    const saved = localStorage.getItem("language") as Language | null;
    if (saved) setLanguageState(saved);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    const translations: Record<Language, Record<string, string>> = {
      de: {
        "nav.services": "Leistungen",
        "nav.events": "Veranstaltungen",
        "nav.about": "Über Uns",
        "nav.contact": "Kontakt",
        "nav.request": "Anfrage stellen",
        "hero.location": "Wuppertal · Deutschland · Österreich · Schweiz",
        "hero.title1": "Wir bringen",
        "hero.title2": "Ihren Sound",
        "hero.title3": "zum Leben",
        "hero.subtitle": "Professionelle PA-Systeme, Lichtanlagen, DJs und Entertainmentservices für Festivals, Hochzeiten und private Veranstaltungen.",
        "hero.btn1": "Unsere Leistungen",
        "hero.btn2": "Jetzt anfragen",
        "hero.scroll": "Scrollen",
        "stats.events": "Events realisiert",
        "stats.experience": "Jahre Erfahrung",
        "stats.countries": "Länder",
        "stats.satisfaction": "Kundenzufriedenheit",
        "services.label": "Was wir bieten",
        "services.title": "Unsere Leistungen",
        "services.pa.title": "PA-Systeme",
        "services.pa.subtitle": "Professionelle Beschallung",
        "services.pa.desc": "Von kleinen Privatfeiern bis hin zu großen Festivals — wir liefern und betreiben professionelle PA-Systeme der neuesten Generation. Line-Array-Systeme, Subwoofer, Monitore und vollständige Signalketten für kristallklaren Sound.",
        "services.pa.f1": "Line-Array-Systeme",
        "services.pa.f2": "Subwoofer & Monitore",
        "services.pa.f3": "Digitale Mischpulte",
        "services.pa.f4": "Technischer Support vor Ort",
        "services.lighting.title": "Lichtanlagen",
        "services.lighting.subtitle": "Atmosphäre & Bühnenlicht",
        "services.lighting.desc": "Unsere professionellen Lichtanlagen verwandeln jeden Raum in ein Erlebnis. Moving Heads, Beam-Lights, LED-Wände, Hazer und Uplighting — wir erschaffen die perfekte Atmosphäre für Ihr Event.",
        "services.lighting.f1": "Moving Head Spots",
        "services.lighting.f2": "Beam & Wash Lights",
        "services.lighting.f3": "LED-Wände & Strips",
        "services.lighting.f4": "Hazer & Nebelmaschinen",
        "services.dj.title": "DJ-Service",
        "services.dj.subtitle": "Musik für jeden Anlass",
        "services.dj.desc": "Unsere erfahrenen DJs lesen die Stimmung und sorgen für eine unvergessliche Tanzfläche. Von Hochzeits-Playlist bis hin zu Festival-Headliner-Sets — wir haben den richtigen Sound für Ihren Anlass.",
        "services.dj.f1": "Hochzeits-DJs",
        "services.dj.f2": "Festival & Club-DJs",
        "services.dj.f3": "Moderations-Service",
        "services.dj.f4": "Komplette Musikplanung",
        "services.entertainment.title": "Entertainment",
        "services.entertainment.subtitle": "Tänzer & Show-Acts",
        "services.entertainment.desc": "Für besondere Momente bieten wir professionelle Tänzer und Show-Acts an. Von eleganten Showdance-Performances bis hin zu energiegeladenen Tanzshows — wir bringen Ihre Veranstaltung auf ein neues Level.",
        "services.entertainment.f1": "Professionelle Tänzer",
        "services.entertainment.f2": "Showdance & Choreografie",
        "services.entertainment.f3": "Thematische Performances",
        "services.entertainment.f4": "Komplettpaket buchbar",
        "events.label": "Für jeden Anlass",
        "events.title": "Veranstaltungsarten",
        "events.festivals": "Festivals",
        "events.festivals.desc": "Wir sind erfahren in der Ausstattung und dem Betrieb von Outdoor- und Indoor-Festivals jeder Größe. Vom kleinen Stadtfest bis zum mehrtägigen Musikfestival.",
        "events.weddings": "Hochzeiten",
        "events.weddings.desc": "Ihr besonderer Tag verdient den perfekten Sound. Wir sorgen für eine unvergessliche Atmosphäre — vom Standesamt bis zur Tanzfläche.",
        "events.private": "Private Feiern",
        "events.private.desc": "Geburtstage, Firmenevents, Jubiläen — wir bringen professionelle Veranstaltungstechnik zu Ihnen nach Hause oder in Ihre Eventlocation.",
        "about.label": "Wer wir sind",
        "about.title": "Leidenschaft für den perfekten Sound",
        "about.p1": "BLACK GIANT SOUNDS ist Ihr professioneller Partner für Veranstaltungstechnik und Entertainment im deutschsprachigen Raum. Mit Sitz in Wuppertal betreuen wir Events in Deutschland, Österreich und der Schweiz.",
        "about.p2": "Unser Team vereint jahrelange Erfahrung in der Veranstaltungstechnik mit echter Leidenschaft für Musik und Performance. Wir verstehen, dass jedes Event einzigartig ist — deshalb entwickeln wir für jeden Kunden maßgeschneiderte Lösungen.",
        "about.p3": "Von der ersten Beratung bis zum letzten Beat nach Ihrem Event — wir sind für Sie da.",
        "about.location": "Wuppertal, Deutschland",
        "about.region": "DE · AT · CH",
        "testimonials.label": "Was unsere Kunden sagen",
        "testimonials.title": "Stimmen unserer Kunden",
        "testimonials.t1": "BLACK GIANT SOUNDS hat unsere Hochzeit zu einem unvergesslichen Erlebnis gemacht. Der Sound war perfekt, die Lichtstimmung traumhaft.",
        "testimonials.a1": "Sarah & Markus K.",
        "testimonials.e1": "Hochzeit, Düsseldorf",
        "testimonials.t2": "Für unser Stadtfest haben wir zum dritten Mal mit BGS zusammengearbeitet. Professionell, zuverlässig und immer mit einem Lächeln.",
        "testimonials.a2": "Thomas B.",
        "testimonials.e2": "Stadtfest Wuppertal",
        "testimonials.t3": "Die DJ-Performance und die Lichtshow haben unsere Firmenfeier auf ein ganz neues Level gebracht. Absolut empfehlenswert!",
        "testimonials.a3": "Christine M.",
        "testimonials.e3": "Firmenevent, Köln",
        "contact.label": "Bereit für Ihr Event?",
        "contact.title": "Lassen Sie uns gemeinsam planen",
        "contact.subtitle": "Schildern Sie uns Ihr Event und wir erstellen Ihnen ein maßgeschneidertes Angebot. Wir melden uns innerhalb von 24 Stunden bei Ihnen.",
        "contact.email.label": "E-Mail",
        "contact.location.label": "Standort",
        "contact.region.label": "Einsatzgebiet",
        "contact.form.name": "Name *",
        "contact.form.name.placeholder": "Ihr vollständiger Name",
        "contact.form.email": "E-Mail *",
        "contact.form.email.placeholder": "ihre@email.de",
        "contact.form.phone": "Telefon",
        "contact.form.phone.placeholder": "+49 ...",
        "contact.form.eventtype": "Veranstaltungsart *",
        "contact.form.eventtype.select": "Bitte wählen",
        "contact.form.eventtype.festival": "Festival",
        "contact.form.eventtype.wedding": "Hochzeit",
        "contact.form.eventtype.private": "Private Feier",
        "contact.form.eventtype.corporate": "Firmenevent",
        "contact.form.eventtype.other": "Sonstiges",
        "contact.form.date": "Datum der Veranstaltung",
        "contact.form.message": "Ihre Nachricht *",
        "contact.form.message.placeholder": "Beschreiben Sie Ihr Event, den Veranstaltungsort, die erwartete Gästezahl und welche Leistungen Sie benötigen...",
        "contact.form.submit": "Anfrage absenden",
        "contact.success.title": "Vielen Dank!",
        "contact.success.message": "Ihre Anfrage wurde erfolgreich versendet. Wir melden uns so schnell wie möglich bei Ihnen.",
        "footer.desc": "Professionelle PA-Systeme, Lichtanlagen und Entertainment für unvergessliche Events.",
        "footer.nav": "Navigation",
        "footer.contact": "Kontakt",
        "footer.copyright": "© BLACK GIANT SOUNDS. Alle Rechte vorbehalten.",
        "footer.region": "Wuppertal · Deutschland · Österreich · Schweiz",
      },
      en: {
        "nav.services": "Services",
        "nav.events": "Events",
        "nav.about": "About Us",
        "nav.contact": "Contact",
        "nav.request": "Request Quote",
        "hero.location": "Wuppertal · Germany · Austria · Switzerland",
        "hero.title1": "We bring",
        "hero.title2": "your sound",
        "hero.title3": "to life",
        "hero.subtitle": "Professional PA systems, lighting rigs, DJs, and entertainment services for festivals, weddings, and private events.",
        "hero.btn1": "Our Services",
        "hero.btn2": "Get a Quote",
        "hero.scroll": "Scroll",
        "stats.events": "Events delivered",
        "stats.experience": "Years of experience",
        "stats.countries": "Countries",
        "stats.satisfaction": "Customer satisfaction",
        "services.label": "What we offer",
        "services.title": "Our Services",
        "services.pa.title": "PA Systems",
        "services.pa.subtitle": "Professional Sound",
        "services.pa.desc": "From intimate private events to large-scale festivals — we supply and operate state-of-the-art PA systems. Line-array systems, subwoofers, monitors, and complete signal chains for crystal-clear sound.",
        "services.pa.f1": "Line-Array Systems",
        "services.pa.f2": "Subwoofers & Monitors",
        "services.pa.f3": "Digital Mixing Consoles",
        "services.pa.f4": "On-site Technical Support",
        "services.lighting.title": "Lighting Rigs",
        "services.lighting.subtitle": "Atmosphere & Stage Lighting",
        "services.lighting.desc": "Our professional lighting systems transform any space into an experience. Moving heads, beam lights, LED walls, hazers, and uplighting — we create the perfect atmosphere for your event.",
        "services.lighting.f1": "Moving Head Spots",
        "services.lighting.f2": "Beam & Wash Lights",
        "services.lighting.f3": "LED Walls & Strips",
        "services.lighting.f4": "Hazers & Fog Machines",
        "services.dj.title": "DJ Service",
        "services.dj.subtitle": "Music for Every Occasion",
        "services.dj.desc": "Our experienced DJs read the crowd and keep the dance floor alive. From wedding playlists to festival headliner sets — we have the right sound for your event.",
        "services.dj.f1": "Wedding DJs",
        "services.dj.f2": "Festival & Club DJs",
        "services.dj.f3": "MC Services",
        "services.dj.f4": "Complete Music Planning",
        "services.entertainment.title": "Entertainment",
        "services.entertainment.subtitle": "Dancers & Show Acts",
        "services.entertainment.desc": "For special moments, we offer professional dancers and show acts. From elegant showdance performances to high-energy dance shows — we take your event to the next level.",
        "services.entertainment.f1": "Professional Dancers",
        "services.entertainment.f2": "Showdance & Choreography",
        "services.entertainment.f3": "Themed Performances",
        "services.entertainment.f4": "Complete Package Available",
        "events.label": "For Every Occasion",
        "events.title": "Event Types",
        "events.festivals": "Festivals",
        "events.festivals.desc": "We have extensive experience equipping and operating outdoor and indoor festivals of all sizes. From small city festivals to multi-day music festivals.",
        "events.weddings": "Weddings",
        "events.weddings.desc": "Your special day deserves perfect sound. We create an unforgettable atmosphere — from the ceremony to the dance floor.",
        "events.private": "Private Events",
        "events.private.desc": "Birthdays, corporate events, anniversaries — we bring professional event technology to your home or venue.",
        "about.label": "Who We Are",
        "about.title": "Passion for Perfect Sound",
        "about.p1": "BLACK GIANT SOUNDS is your professional partner for event technology and entertainment in the German-speaking region. Based in Wuppertal, we serve events in Germany, Austria, and Switzerland.",
        "about.p2": "Our team combines years of event technology experience with genuine passion for music and performance. We understand that every event is unique — that's why we develop customized solutions for each client.",
        "about.p3": "From the first consultation to the last beat after your event — we're here for you.",
        "about.location": "Wuppertal, Germany",
        "about.region": "DE · AT · CH",
        "testimonials.label": "What Our Clients Say",
        "testimonials.title": "Client Testimonials",
        "testimonials.t1": "BLACK GIANT SOUNDS made our wedding an unforgettable experience. The sound was perfect, the lighting atmosphere was magical.",
        "testimonials.a1": "Sarah & Markus K.",
        "testimonials.e1": "Wedding, Düsseldorf",
        "testimonials.t2": "We've worked with BGS three times for our city festival. Professional, reliable, and always with a smile.",
        "testimonials.a2": "Thomas B.",
        "testimonials.e2": "City Festival Wuppertal",
        "testimonials.t3": "The DJ performance and light show took our corporate event to the next level. Highly recommended!",
        "testimonials.a3": "Christine M.",
        "testimonials.e3": "Corporate Event, Cologne",
        "contact.label": "Ready for Your Event?",
        "contact.title": "Let's Plan Together",
        "contact.subtitle": "Tell us about your event and we'll create a customized quote. We'll get back to you within 24 hours.",
        "contact.email.label": "Email",
        "contact.location.label": "Location",
        "contact.region.label": "Service Area",
        "contact.form.name": "Name *",
        "contact.form.name.placeholder": "Your full name",
        "contact.form.email": "Email *",
        "contact.form.email.placeholder": "your@email.com",
        "contact.form.phone": "Phone",
        "contact.form.phone.placeholder": "+49 ...",
        "contact.form.eventtype": "Event Type *",
        "contact.form.eventtype.select": "Please select",
        "contact.form.eventtype.festival": "Festival",
        "contact.form.eventtype.wedding": "Wedding",
        "contact.form.eventtype.private": "Private Event",
        "contact.form.eventtype.corporate": "Corporate Event",
        "contact.form.eventtype.other": "Other",
        "contact.form.date": "Event Date",
        "contact.form.message": "Your Message *",
        "contact.form.message.placeholder": "Describe your event, venue, expected guest count, and which services you need...",
        "contact.form.submit": "Submit Request",
        "contact.success.title": "Thank You!",
        "contact.success.message": "Your request has been sent successfully. We'll get back to you as soon as possible.",
        "footer.desc": "Professional PA systems, lighting rigs, and entertainment for unforgettable events.",
        "footer.nav": "Navigation",
        "footer.contact": "Contact",
        "footer.copyright": "© BLACK GIANT SOUNDS. All rights reserved.",
        "footer.region": "Wuppertal · Germany · Austria · Switzerland",
      },
    };

    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
